### ISSUE TITLE
Ground-Truth missing

### ISSUE THREAD

**Issue by pouyashiri** [DIAGNijmegen/picai_labels#12]
We are doing research using this data, it seems like ground-truth for the following Radical Prostatectomy cases is missing:
10013
10053
10229
10282
10377
10399
10402
10519
10865
10873
10883
11072

Please let me know if you could help with providing these.

**Comment by joeranbosma** [comment]
Hi @pouyashiri,

You are correct, these patients indeed received a radical prostatectomy, which came back positive (GS >= 7) (I double-checked the first three).

No manual voxel-level annotations were made for these cases, these are also not available in our archives. The reason for this is the setup of PI-CAI: manually annotating at the voxel-level all 10,000+ cases in the PI-CAI challenge (public + sequestered training data + tuning cohort + testing cohort) is infeasible (we did annotate all at a case-level). For the PI-CAI challenge, we observed that all top-5 solutions used semi-supervised learning to improve performance, with most teams using the AI-derived lesion segmentations provided here: https://github.com/DIAGNijmegen/picai_labels/tree/main/csPCa_lesion_delineations/AI/Bosma22a.

There you can also find the AI-derived annotations for the patients you linked. For more information about how these annotations were derived, please see https://pubs.rsna.org/doi/10.1148/ryai.230031.
