### ISSUE TITLE
Inconsistent number of voxels between resampled annotation and t2w

### ISSUE THREAD

**Issue by ChristophNeukirchenAtPhilipsCom** [DIAGNijmegen/picai_labels#3]
After the update of labeI data (mid June 2022) is there a mismatch between T2W and resampled annotations in number of voxels for the following case?
* T2W
 images/fold0-4/10691/10691_1000707_t2w.mha :
  center: -37.663136  33.162276 -70.192629
  extent: 192.000000 192.000000  75.599997
 axis[0]:   1.000000   0.000000  -0.000000
 axis[1]:  -0.000000   0.993961  -0.109734
 axis[2]:  -0.000000   0.109734   0.993961
    size: 384 384 21
voxelgap:   0.000000   0.000000   0.000000

* Resampled annotation
human_expert/resampled/10691_1000707.nii.gz :
  center: -37.563128  33.261668 -70.203641
  extent: 192.000008 192.000008  68.399908
 axis[0]:   1.000000  -0.000000  -0.000000
 axis[1]:  -0.000000   0.993961  -0.109734
 axis[2]:   0.000000   0.109734   0.993961
    size: 640 640 19
voxelgap:   0.000000   0.000000   0.000000

Maybe getting the corresponding correct T2W is a bit misleading because the Zenodo page (https://zenodo.org/record/6624726) still names the updated MRI data as V1.0 from May 5, 2022.

greetings, Christoph

**Comment by joeranbosma** [comment]
Hi Christoph,

Thanks for raising this issue! You are completely correct, the annotation for study 1000707 of patient 10691 was resampled to the wrong T2-weighted scan. I have resampled this annotation to the correct scan now, see [picai_labels](https://github.com/DIAGNijmegen/picai_labels/commit/01625369df79dbdc97c1ea478beaf8764a132539) for the update.

Also, I have updated the imaging metadata, to correctly reflect the release is v2.0 and it was released on June 10th.

Kind regards,
Joeran
