### ISSUE TITLE
Annotated case IDs

### ISSUE THREAD

**Issue by xychen2022** [DIAGNijmegen/picai_labels#4]
Hi,

Is there a file that keep a record of the ID of cases that have ground truth labels? I think it would be better for participators to use the data if such a file is available. 

Thanks, 
Xiaoyang

**Comment by joeranbosma** [comment]
Hi @xychen2022,

We have a list available in the accompanying repository [picai_baseline](https://github.com/DIAGNijmegen/picai_baseline). When you have this installed, you can access this list by importing it from Python:

```python
from picai_baseline.splits import subject_list_annotated
```

We have also prepared cross-validation splits, both for the full dataset of 1500 cases and the manually annotated subset of 1295 cases. You can find details about that here: https://github.com/DIAGNijmegen/picai_baseline#cross-validation-splits. There, we also provide instructions on how to export the cross-validation splits to files. 

Hope this helps, let me know if you have any more queries. 
Joeran
