### ISSUE TITLE
About human_expert label

### ISSUE THREAD

**Issue by LinxuanHan** [DIAGNijmegen/picai_labels#8]
Dear admin,
  sorry to bother you.
  The labels in  csPCa_lesion_delineations/human_expert  and  csPCa_lesion_delineations/AI/Bosma22a have some issue, the content of the label file is zero both background and foreground.
  could you please answer the question? 
  good luck.

**Comment by joeranbosma** [comment]
Hi @LinxuanHan,

For negative cases (approximately 2/3 of cases) the annotations are empty, indicating that case did not harbor clinically significant prostate cancer.
For example case nr 32 had a clear tumor and therefore the label is not empty.

Hope this helps,
Joeran

**Comment by LinxuanHan** [comment]
Hi Joeran，
Thank you for your answer ,this helps me a lot. But I have other questions hope you can give me some tricks:
1、Can I use the AI labels to train a  AI model aiming to segment ISUP≤1 and ISUP≥2 ？Because the labels were labeled by AI Model，I use it to deal with same thing，it looks like a bootstrap task。
2、The file in clinical_information/marksheet.csv ， about lines 12th，case_csPCA, does it mean  the patient has csPCA and the csPCA is positive? (Table where "Yes" positive , "No" negetive ? or all the patients are csPCA positive but "Yes" table means ISUP≥2 “No" table means ISUP≤1) 
gool luck！

**Comment by joeranbosma** [comment]
Hi @LinxuanHan,

1. You can use the AI labels to train an AI model to segment ISUP ≥ 2 lesions (as indicated by the [label map in the picai_labels repository](https://github.com/DIAGNijmegen/picai_labels#label-mapping-of-cspca-annotations)). ISUP ≤ 1 lesions are not annotated (label 0) and are therefore indistinguishable from the background (also 0).
2. Having at least one csPCa lesion (ISUP ≥ 2) means the case is positive, and case_csPCa is "Yes". Lesions with ISUP 1 are not csPCa, as these indicate indolent cancer. So indeed,  "Yes" means ISUP≥2 and “No" means ISUP≤1.

**Comment by LinxuanHan** [comment]
Hi Joeran

About last question 1 , AI labels have 3 content ,  I konw label 0 is background , but what do label 1 and label2 mean?
src="https://github.com/DIAGNijmegen/picai_labels/assets/48483218/fd52223f-9755-4860-a1d1-18afd7bbcf1c">

**Comment by joeranbosma** [comment]
Hi @LinxuanHan,

The image you linked seems to be of a zonal prostate annotation! My answers above assumed you were asking about the lesion annotations (from csPCa_lesion_delineations).

Could you indicate from which folder the annotation is that you now have a question about? And what's the filename?

**Comment by LinxuanHan** [comment]
Hi Joeran,
 Sorry Joeran, it's my fault. The filename is \picai_labels-main\anatomical_delineations\zonal_pz_tz\AI\HeviAI23\10000_1000000.nii.gz, and I have already known why there are three kinds of labels ,according to your answer above. Because labels in zonal_pz_tz  are about prostate zone , maybe Label 1  and Label 2 are pz and tz.
So if I want to segment prostate and ISUP≥2，Can I use labels in anatomical_delineations\zonal_pz_tz\AI\Yuan23 and labels in csPCa_lesion_delineations\AI\Bosma22a  at the same time ?

**Comment by joeranbosma** [comment]
Yes that's right!
