### ISSUE TITLE
PI-RADS information

### ISSUE THREAD

**Issue by ericKuo722** [DIAGNijmegen/picai_labels#9]
Hi Admin,

Could you please share the information on which patient is in a PI-RADS level 3,4 and 5 by any chance?
I wonder how do people analyse final segmentation performance based on PI-RADS because I didn't find them.

Thank you very much!
Eric

**Comment by joeranbosma** [comment]
Hi Eric,

Thanks for you request. We will discuss this internally and get back to you.

Best,
Joeran

**Comment by ericKuo722** [comment]
Hi Joeran, thanks for your quick respond! Yah, thank you very much and look forward to hearing from you.

**Comment by joeranbosma** [comment]
Dear @ericKuo722,

Unfortunately we will not release this information any time soon. You can, however, evaluate performance based on the current annotations (based on biopsy + MRI), which provides a much stronger reference standard. We are currently drafting a journal publication where we do compare radiologists' performance (PI-RADS) against the strongest possible reference standard, so stay tuned for that!

Best,
Joeran
